# Generated by Django 5.2.6 on 2025-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Название источника')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на статью')),
                ('url_to_image', models.URLField(blank=True, null=True, verbose_name='Ссылка на картинку статьи')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['published_at'],
            },
        ),
    ]
