# Generated by Django 5.2.6 on 2025-09-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
    ]
