# Generated by Django 5.2.6 on 2025-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code_experetion_date',
            field=models.DateTimeField(null=True, verbose_name='Срок годности кода'),
        ),
    ]
