# Generated by Django 5.2.6 on 2025-09-17 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_code_experetion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Код активации(захеширован)'),
        ),
    ]
