# Generated by Django 5.2.6 on 2025-09-17 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('fca375f7-7f71-4cb4-b494-a2932ed62363'), unique=True, verbose_name='Код активации(захеширован)'),
        ),
    ]
