# Generated by Django 5.2.6 on 2025-09-17 12:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activation_code',
            field=models.UUIDField(default=uuid.UUID('a7ebceb2-d488-41c6-940b-5ec271ec8e33'), unique=True, verbose_name='Код активации(захеширован)'),
        ),
    ]
