# Generated by Django 5.2.6 on 2025-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='activation_code',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Код активации'),
        ),
    ]
